-- ═══════════════════════════════════════════════════════════════
-- pr_boxmoves : bin → bin box-move log
-- Run this once in the Supabase SQL editor.
-- Until it exists, the app still works — moves just aren't recorded.
-- After it exists, every bin→bin move shows in the Activity Log
-- (📍 Bin Move) and in each bin's 📜 history.
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.pr_boxmoves (
  id        bigint generated by default as identity primary key,
  at        timestamptz not null default now(),
  by_email  text,
  wh        text,
  style     text,
  color     text,
  size      text,
  from_loc  text,
  to_loc    text,
  boxes     integer,
  pcs       integer,
  box_ids   jsonb
);

-- fast lookups for the per-bin history (from OR to this bin) and the log
create index if not exists pr_boxmoves_from_idx on public.pr_boxmoves (style, color, size, from_loc);
create index if not exists pr_boxmoves_to_idx   on public.pr_boxmoves (style, color, size, to_loc);
create index if not exists pr_boxmoves_at_idx    on public.pr_boxmoves (at desc);

-- same anon access pattern the other log tables use
alter table public.pr_boxmoves enable row level security;

drop policy if exists pr_boxmoves_all on public.pr_boxmoves;
create policy pr_boxmoves_all on public.pr_boxmoves
  for all to anon, authenticated
  using (true) with check (true);

grant all on public.pr_boxmoves to anon, authenticated;
